### PR TITLE
Linked list update

### PR DESCRIPTION
**Pull request by Hyang0219**
Hi, I have made below changes:
1. added self.length as a class attribute
2. added if statement for prepend() so that to define self.tail when the linked list is empty. (same as append)
3. added insert2() and remove2() using traverse() functions, the same solution shown in the Udemy course

Please let me know if I need to change anything. thanks.

### CODE REVIEW

**Review by theja-m — COMMENTED** [review]
Old Iter function is good, Only change I could see is on the (for loop where 0 is redundant). I have included zero for better understanding.

Thanks

**Review by theja-m — CHANGES_REQUESTED** [review]
Remove the old functions and modify the full implementation and raise PR with the new functions. I will test and merge the pull request.

Thanks

**Comment by Hyang0219** [comment]
> Old Iter function is good, Only change I could see is on the (for loop where 0 is redundant). I have included zero for better understanding.
> 
> Thanks

Hi, thanks for the reply. I suppose this comment is for the First Recurring Character.py.
the func(mylist) and hashtable(mylist) are actually giving different answers, 1 and 2 respectviely.
The change was made to make sure func() gives the same solution as hashtable() (this was left an open exercise in the course).
please ignore if you were intended to show two different solutions.
Regards,
Hanlin

**Comment by Hyang0219** [comment]
> Remove the old functions and modify the full implementation and raise PR with the new functions. I will test and merge the pull request.
> 
> Thanks

I have updated the linked list file.
Just a quickie, I can see both the changes I committed (hashtable & linked list) in the linked list PR, but I was only supposed to commit one on itself. not sure why that happened and how do I deleted the hashtable change from the linked list PR?

Regards,
Hanlin

**Comment by theja-m** [comment]
I am ready to merge the pull request only for the linked list, for the First recurring character I have left it on purpose. Maybe you can try to add more comments how both the iter function differs(one in tutorial and the exercise one)

Thanks, 
Theja

**Comment by Hyang0219** [comment]
Hi hope you are well,
Are you okay to merge or do you want more changes?
or I shall delete the change on the recurring exercise from this pull request?
Regards,
Hanlin

**Comment by theja-m** [comment]
Hi,

Delete the commit for firstrecurringcharacter.py , I will merge the PR then.

Thanks,
Theja

**Pull request closed without merging**
